Repository Lilypad-Tech/lilypad, pull requests merged in 2024-11, with the labels that each got.

#418 feat: Add job creator CLI run trace
  pkg/jobcreator/run.go
Labels: feature, cla-signed

#419 feat: Add solver rate limiter
  go.mod
  go.sum
  pkg/http/types.go
  pkg/options/server.go
  pkg/solver/server.go
  stack
  test/ratelimit_test.go
Labels: feature, cla-signed

#423 feat: Add custom retryablehttp error handler
  .github/workflows/test.yml
  pkg/http/utils.go
  pkg/solver/controller.go
  test/integration_test.go
Labels: feature, cla-signed

#426 chore: added my name to contributing licensing agreement
  .clabot
  NOTICES.md
Labels: chore

#425 chore: Creating a template for devs to fill out for new features or functionality
  .github/ISSUE_TEMPLATE/issue--developer-.md
Labels: chore, cla-signed

#428 chore: Updated Issue Template
  .github/ISSUE_TEMPLATE/developer_issue.md
  assets/issue-tags.png
Labels: chore, cla-signed

#436 chore: ignore chain data directory
  .gitignore
Labels: chore, cla-signed

#427 fix: solver connection errors
  pkg/solver/controller.go
  pkg/solver/server.go
Labels: fix, cla-signed

#432 refactor: Use cleanup manager to unsubscribe web3 subscriptions
  pkg/web3/events_jobcreator.go
  pkg/web3/events_mediation.go
  pkg/web3/events_payments.go
  pkg/web3/events_pow.go
  pkg/web3/events_storage.go
  pkg/web3/events_token.go
  pkg/web3/utils.go
Labels: refactor, cla-signed, solver, job creation, mediation, resource-provider

#438 fix: run bacalhau in a separate container
  .github/workflows/test.yml
  .local.dev
  docker/bacalhau/Dockerfile
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  docker/resource-provider/Dockerfile
  pkg/executor/bacalhau/bacalhau.go
  stack
  test/ratelimit_test.go
Labels: fix, cla-signed

#448 chore: Fix typos
  DEVNET.md
  LOCAL_DEVELOPMENT.md
  docs/smart-contract-jobs.md
Labels: chore, cla-signed

#435 feat: Add solver metrics
  cmd/lilypad/jobcreator.go
  cmd/lilypad/resource-provider.go
  cmd/lilypad/run.go
  cmd/lilypad/solver.go
  cmd/lilypad/utils.go
  go.mod
  go.sum
  pkg/options/otel.go
  pkg/options/solver.go
  pkg/solver/controller.go
  pkg/solver/matcher/matcher.go
  pkg/solver/matcher/metric.go
  pkg/solver/metric.go
  pkg/solver/solver.go
  pkg/solver/store/memory/store.go
  pkg/solver/store/types.go
  pkg/system/metric.go
  pkg/system/otel.go
Labels: feature, cla-signed

#449 refactor: Refactor solver store helpers
  pkg/solver/store/memory/store.go
  pkg/solver/store/store.go
Labels: refactor

#451 chore: CLA Signed for Phil
  .clabot
  NOTICES.md
Labels: chore

#453 feat: demonet network config
  hardhat/hardhat.config.ts
  pkg/options/configs/demonet.toml
Labels: feature, cla-signed

#454 chore: Removed the api check for the api_host
  pkg/options/services.go
Labels: chore, cla-signed

#452 feat: add base services compose file
  LOCAL_DEVELOPMENT.md
  docker/docker-compose.base.yml
  docker/docker-compose.dev.yml
  stack
  test/integration_test.go
Labels: feature, cla-signed

#456 fix: Silence web3 event listener cancellation errors
  go.mod
  go.sum
  pkg/jobcreator/controller.go
  pkg/jobcreator/onchain_jobcreator.go
  pkg/mediator/controller.go
  pkg/resourceprovider/controller.go
  pkg/solver/controller.go
  pkg/web3/events.go
  pkg/web3/events_jobcreator.go
  pkg/web3/events_mediation.go
  pkg/web3/events_payments.go
  pkg/web3/events_pow.go
  pkg/web3/events_storage.go
  pkg/web3/events_token.go
  pkg/web3/types.go
Labels: fix, cla-signed
