Repository Lilypad-Tech/lilypad, pull requests merged in 2024-10, with the labels that each got.

#400 feat: Add IPFS client to retrieve results
  LOCAL_DEVELOPMENT.md
  cmd/lilypad/mediator.go
  cmd/lilypad/resource-provider.go
  docker/docker-compose.dev.yml
  go.mod
  go.sum
  pkg/executor/bacalhau/bacalhau.go
  pkg/ipfs/client.go
  pkg/ipfs/ipfs.go
  pkg/mediator/mediator.go
  pkg/options/config.go
  pkg/options/configs/dev.toml
  pkg/options/configs/devnet.toml
  pkg/options/configs/testnet.toml
  pkg/options/ipfs.go
  pkg/options/mediator.go
  pkg/options/resource-provider.go
  pkg/resourceprovider/resourceprovider.go
  stack
Labels: feature, cla-signed

#396 fix: re-register resource offers after runJob
  go.mod
  go.sum
  pkg/resourceprovider/controller.go
Labels: fix, cla-signed

#397 refactor: Move targeting into a function
  pkg/solver/matcher/matcher.go
Labels: refactor, cla-signed

#390 feat: Add get_ethclient trace
  pkg/web3/sdk.go
Labels: feature, cla-signed

#403 fix: lower default pricing and check LP balance
  pkg/solver/controller.go
  pkg/web3/sdk.go
  pkg/web3/sdk_test.go
Labels: fix, cla-signed

#404 feat: add docker compose for RPs
  docker/docker-compose.yml
Labels: feature, cla-signed

#336 feat: Add deal making trace
  pkg/data/utils.go
  pkg/options/resource-provider.go
  pkg/solver/controller.go
  pkg/solver/matcher/match.go
  pkg/solver/matcher/matcher.go
Labels: feature, cla-signed

#408 feat: Add Lilypad version HTTP header
  pkg/http/utils.go
  pkg/solver/server.go
Labels: feature, cla-signed

#410 chore: Remove CommandContext.CommandContext
  pkg/system/context.go
Labels: chore, cla-signed

#411 feat: Add job creator tracer
  .github/workflows/test.yml
  cmd/lilypad/jobcreator.go
  cmd/lilypad/run.go
  pkg/jobcreator/controller.go
  pkg/jobcreator/jobcreator.go
  pkg/jobcreator/onchain_jobcreator.go
  pkg/jobcreator/run.go
  pkg/options/job-creator.go
  test/integration_test.go
Labels: feature, cla-signed

#415 fix: add version info to RP Docker build
  .github/workflows/release_docker.yml
  docker/docker-compose.dev.yml
  docker/resource-provider/Dockerfile
  docker/solver/Dockerfile
  stack
Labels: fix, cla-signed

#416 fix: Handle accept result and download result errors
  pkg/jobcreator/controller.go
Labels: fix, cla-signed
