Repository Lilypad-Tech/lilypad, pull requests merged in 2024-08, with the labels that each got.

#266 fix: reconnect sc event loop
  pkg/http/utils.go
  pkg/web3/events.go
  pkg/web3/events_jobcreator.go
  pkg/web3/events_mediation.go
  pkg/web3/events_payments.go
  pkg/web3/events_pow.go
  pkg/web3/events_storage.go
  pkg/web3/events_token.go
Labels: fix

#273 chore: Add security policy
  SECURITY.md
Labels: chore

#277 chore: limit docker log size
  .github/workflows/devnet_deploy.yml
  .github/workflows/testnet_deploy_services.yml
Labels: chore

#282 revert: removes gpc options check
  cmd/lilypad/jobcreator.go
  cmd/lilypad/mediator.go
  cmd/lilypad/resource-provider.go
  cmd/lilypad/run.go
  cmd/lilypad/solver.go
  pkg/options/deprecation.go
Labels: revert

#284 chore: use latest nitro node for local chain
  stack
Labels: chore

#281 build: add integration tests
  .github/workflows/test.yml
  docker/docker-compose.dev.yml
  stack
  test/integration_test.go
Labels: build

#290 chore: Add README.md
  hardhat/README.md
Labels: chore

#294 chore: Ignore Hardhat Openzeppelin outputs
  .gitignore
Labels: chore

#286 fix: remove ntfs zone files
  hardhat/deployments/testnet/.chainId:Zone.Identifier
  hardhat/deployments/testnet/.migrations.json:Zone.Identifier
  hardhat/deployments/testnet/ExampleClient.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadController.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadMediationRandom.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadOnChainJobCreator.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadPayments.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadPow.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadStorage.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadToken.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadUsers.json:Zone.Identifier
  hardhat/deployments/testnet/solcInputs/4da1c3755a4d6211296e1fdf692059eb.json:Zone.Identifier
  hardhat/deployments/testnet/solcInputs/648c61a8a804e137d75320a74adaf899.json:Zone.Identifier
Labels: fix

#297 chore: fix typo in release.yml
  .github/workflows/release.yml
Labels: chore

#302 chore: Update pull request template
  .github/pull_request_template.md
Labels: chore

#298 feat: Add ETH Balance Check on RP Matching
  pkg/data/types.go
  pkg/solver/controller.go
  pkg/web3/sdk.go
  pkg/web3/utils.go
Labels: feature

#299 fix: gpu support for rp Dockerfile
  docker/docker-compose.dev.yml
  docker/resource-provider/Dockerfile
Labels: fix

#300 docs: update Bacalhau install instructions
  LOCAL_DEVELOPMENT.md
Labels: documentation

#291 refactor: remove doppler depedency from local development
  .github/workflows/test.yml
  .local.dev
  LOCAL_DEVELOPMENT.md
  docker/docker-compose.dev.yml
  docker/job-creator/Dockerfile
  docker/solver/Dockerfile
  stack
  test/integration_test.go
Labels: refactor

#306 chore: add issues_templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: chore

#309 chore: add contributing guide
  CONTRIBUTING.md
Labels: chore

#310 chore: Fix broken links
  CONTRIBUTING.md
Labels: chore

#314 chore: sign CLA bgins
  .clabot
  NOTICES.md
Labels: chore
