Repository Lilypad-Tech/lilypad, pull requests merged in 2024-09, with the labels that each got.

#318 docs: signs cla agreement
  .clabot
  NOTICES.md
Labels: documentation

#292 feat: Add run job traces
  .github/workflows/release.yml
  .github/workflows/test.yml
  cmd/lilypad/resource-provider.go
  cmd/lilypad/root.go
  cmd/lilypad/run.go
  cmd/lilypad/version.go
  docker/docker-compose.dev.yml
  docker/resource-provider/Dockerfile
  go.mod
  go.sum
  hardhat/.openzeppelin/unknown-412346.json
  hardhat/.openzeppelin/unknown-421614.json
  pkg/jobcreator/run.go
  pkg/options/config.go
  pkg/options/configs/dev.toml
  pkg/options/configs/devnet.toml
  pkg/options/configs/testnet.toml
  pkg/options/otel.go
  pkg/options/resource-provider.go
  pkg/resourceprovider/controller.go
  pkg/resourceprovider/resourceprovider.go
  pkg/system/context.go
  pkg/system/gpu.go
  pkg/system/otel.go
  pkg/system/otel_test.go
  pkg/system/version.go
  pkg/web3/sdk.go
  stack
Labels: feature, cla-signed

#321 docs: signs cla for lilypad-releases
  .clabot
  NOTICES.md
Labels: documentation, cla-signed

#324 chore: Update lilypad-releases[bot] CLA
  .clabot
  NOTICES.md
Labels: chore, cla-signed

#325 build: Removes resource-provider-build-deploy
  .github/workflows/testnet_deploy_services.yml
Labels: build, cla-signed

#328 chore: Add code owners
  .github/CODEOWNERS
Labels: chore, cla-signed

#332 chore: sign CLA Rodebrechtd
  .clabot
  NOTICES.md
Labels: chore

#334 chore: Add GitHub Action for CI Unit Tests
  .github/workflows/test.yml
  hardhat/test/controller.ts
Labels: chore, cla-signed

#340 chore: sign cla + fix typo
  .clabot
  CONTRIBUTING.md
  NOTICES.md
Labels: chore

#341 build: Remove automatic release PR merges
  .github/workflows/release.yml
Labels: build, cla-signed

#347 chore: CLA Signed for Kelindi
  .clabot
  NOTICES.md
Labels: chore

#342 chore: Update .clabot
  .clabot
  NOTICES.md
Labels: chore

#349 chore: CLA Signing
  .clabot
  NOTICES.md
Labels: chore

#350 chore: add alvin-reyes to .clabot/notices
  .clabot
  NOTICES.md
Labels: chore

#338 feat: preflight check for bacalhau version
  cmd/lilypad/resource-provider.go
  go.mod
  go.sum
  pkg/executor/bacalhau/bacalhau.go
  pkg/executor/bacalhau/client.go
  pkg/executor/noop/noop.go
  pkg/executor/types.go
  pkg/options/bacalhau.go
Labels: feature, cla-signed, ready for relase

#348 feat: Changed rpc to Quicknode
  pkg/options/configs/testnet.toml
  pkg/web3/sdk_test.go
Labels: feature, cla-signed

#355 chore: CLA Sign
  .clabot
  NOTICES.md
Labels: chore

#357 chore: Fix docker container to wait Bacalhau status OK
  docker/resource-provider/Dockerfile
Labels: chore, cla-signed

#354 chore: log bacalhau client error
  pkg/executor/bacalhau/bacalhau.go
Labels: chore, cla-signed

#365 feat: added public addresses with failover
  pkg/options/configs/testnet.toml
  pkg/web3/sdk.go
Labels: feature, cla-signed

#363 fix: exclude canceled job offers
  pkg/solver/server.go
  pkg/solver/store/memory/store.go
  pkg/solver/store/types.go
Labels: fix, cla-signed, ready for release

#367 refactor: Update doOffersMatch to matchOffers
  pkg/solver/controller.go
  pkg/solver/matcher/match.go
  pkg/solver/matcher/matcher.go
  pkg/solver/matcher/matcher_test.go
Labels: refactor, cla-signed

#373 chore: sign CLA Sigmund
  .clabot
  NOTICES.md
Labels: chore

#374 test: Fix controller hardhat unit tests
  hardhat/test/controller.ts
  hardhat/test/fixtures.ts
Labels: cla-signed, test

#380 chore: Remove alchemy RPC URL
  pkg/options/configs/testnet.toml
Labels: chore, cla-signed

#384 chore: Add web3 sdk tracers
  cmd/lilypad/jobcreator.go
  cmd/lilypad/mediator.go
  cmd/lilypad/pow_signal.go
  cmd/lilypad/resource-provider.go
  cmd/lilypad/solver.go
  cmd/lilypad/utils.go
  pkg/jobcreator/run.go
  pkg/resourceprovider/controller.go
  pkg/resourceprovider/resourceprovider.go
  pkg/web3/sdk.go
  pkg/web3/sdk_test.go
  test/integration_test.go
Labels: chore, cla-signed

#381 fix: resourceoffer updates
  pkg/resourceprovider/controller.go
Labels: fix, cla-signed

#382 fix: wrong balance err check
  pkg/solver/controller.go
Labels: fix, cla-signed

#371 feat: fetch machine specs from bacalhau
  pkg/data/types.go
  pkg/executor/bacalhau/bacalhau.go
  pkg/executor/bacalhau/client.go
  pkg/executor/noop/noop.go
  pkg/executor/types.go
  pkg/resourceprovider/controller.go
Labels: feature, cla-signed

#388 feat: Add solver HTTP tracing
  cmd/lilypad/resource-provider.go
  cmd/lilypad/solver.go
  docker/docker-compose.dev.yml
  go.mod
  go.sum
  pkg/options/solver.go
  pkg/solver/controller.go
  pkg/solver/server.go
  pkg/solver/solver.go
Labels: feature, cla-signed

#392 chore: Sign CLA mcryptographer
  .clabot
  NOTICES.md
Labels: chore

#393 chore: Add manual testnet deploy trigger
  .github/workflows/testnet_deploy_services.yml
Labels: chore, cla-signed
