Repository Lilypad-Tech/lilypad, pull requests merged in 2024-07, with the labels that each got.

#216 feat: add count function for miners and submissions
  hardhat/.openzeppelin/unknown-412346.json
  hardhat/contracts/LilypadPow.sol
  pkg/web3/bindings/pow/pow.go
Labels: feature

#221 chore: Remove unused Makefile and justfile
  Makefile
  justfile
Labels: chore

#223 build: Update POW contract
  .gitignore
  hardhat/.openzeppelin/unknown-412346.json
  hardhat/.openzeppelin/unknown-421614.json
  hardhat/deploy/010_upgrade_pow.ts
  hardhat/deployments/testnet/.chainId
  hardhat/deployments/testnet/.chainId:Zone.Identifier
  hardhat/deployments/testnet/.migrations.json
  hardhat/deployments/testnet/.migrations.json:Zone.Identifier
  hardhat/deployments/testnet/ExampleClient.json
  hardhat/deployments/testnet/ExampleClient.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadController.json
  hardhat/deployments/testnet/LilypadController.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadMediationRandom.json
  hardhat/deployments/testnet/LilypadMediationRandom.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadOnChainJobCreator.json
  hardhat/deployments/testnet/LilypadOnChainJobCreator.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadPayments.json
  hardhat/deployments/testnet/LilypadPayments.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadPow.json
  hardhat/deployments/testnet/LilypadPow.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadStorage.json
  hardhat/deployments/testnet/LilypadStorage.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadToken.json
  hardhat/deployments/testnet/LilypadToken.json:Zone.Identifier
  hardhat/deployments/testnet/LilypadUsers.json
  hardhat/deployments/testnet/LilypadUsers.json:Zone.Identifier
  hardhat/deployments/testnet/solcInputs/06e78eaee1ee101e9b46d15f399432ba.json
  hardhat/deployments/testnet/solcInputs/4da1c3755a4d6211296e1fdf692059eb.json
  hardhat/deployments/testnet/solcInputs/4da1c3755a4d6211296e1fdf692059eb.json:Zone.Identifier
  hardhat/deployments/testnet/solcInputs/648c61a8a804e137d75320a74adaf899.json
  hardhat/deployments/testnet/solcInputs/648c61a8a804e137d75320a74adaf899.json:Zone.Identifier
  hardhat/deployments/testnet/solcInputs/aa2531d425d99af81546bf5fa8a9513b.json
Labels: build

#219 perf: update cuda algo
  pkg/options/resource-provider.go
  pkg/resourceprovider/cudaminer/config.h
  pkg/resourceprovider/cudaminer/keccak.cu
  pkg/resourceprovider/cudaminer/keccak.cuh
  pkg/resourceprovider/cudaminer/keccak.ptx
  pkg/resourceprovider/cudaworker.go
  pkg/resourceprovider/minerctl.go
  pkg/resourceprovider/resourceprovider.go
Labels: performance

#206 build: Add release pipeline
  .circleci/config.yml
  .github/releases/README.md
  .github/releases/release_notes.md
  .github/workflows/darwin_amd64.yml
  .github/workflows/darwin_arm64.yml
  .github/workflows/linux_amd64.yml
  .github/workflows/linux_arm64.yml
  .github/workflows/release.yml
  .github/workflows/release_binaries.yml
  .github/workflows/testnet_deploy_services.yml
  cmd/lilypad/root.go
  cmd/lilypad/run.go
  cmd/lilypad/version.go
  ops/lilypad-updater-gpu.sh
Labels: build

#227 build: Add releases bootstrap
  .release-please-manifest.json
  release-please-config.json
Labels: build

#218 fix: clean openzeplin proxy deploy metadata
  stack
Labels: fix

#229 build: Add release bootstrap
  .release-please-manifest.json
  release-please-config.json
Labels: build

#230 build: Add release pipeline
  .circleci/config.yml
  .github/releases/README.md
  .github/releases/release_notes.md
  .github/workflows/darwin_amd64.yml
  .github/workflows/darwin_arm64.yml
  .github/workflows/linux_amd64.yml
  .github/workflows/linux_arm64.yml
  .github/workflows/release.yml
  .github/workflows/release_binaries.yml
  .github/workflows/testnet_deploy_services.yml
  cmd/lilypad/root.go
  cmd/lilypad/run.go
  cmd/lilypad/version.go
  ops/lilypad-updater-gpu.sh
Labels: build

#208 chore: update docker context on hardhat processes
  stack
Labels: fix

#234 build: docker releases and compose file
  .github/workflows/release_docker.yml
  .gitignore
  docker/bacalhau/Dockerfile
  docker/chain/Dockerfile
  docker/docker-compose.dev.yml
  docker/job-creator/Dockerfile
  docker/resource-provider/Dockerfile
  docker/solver/Dockerfile
  stack
Labels: build

#220 fix: websocket disconnect and goroutine leak
  pkg/http/websocket_client.go
  pkg/http/websocket_server.go
  pkg/solver/client.go
Labels: fix

#259 docs: docker compose local development instructions
  LOCAL_DEVELOPMENT.md
Labels: documentation

#217 chore: exit early if the current version is not available
  ops/lilypad-updater-gpu.sh
Labels: fix

#260 chore: Add PR labeling again
  .github/workflows/validate_pr_title.yml
Labels: enhancement

#267 chore: Remove PR title labeling
  .github/workflows/validate_pr_title.yml
Labels: chore

#265 chore: remove DisablePow from PersistentFlags
  cmd/lilypad/root.go
Labels: chore

#270 fix: remove auto-updater script
  ops/lilypad-updater-gpu.sh
Labels: help wanted, fix
