Repository Lilypad-Tech/lilypad, pull requests merged in 2024-12, with the labels that each got.

#464 fix: Fix resource offer JSON field name
  pkg/data/types.go
Labels: fix, cla-signed, solver

#463 fix: bacalhau dind w/ nvidia
  docker/bacalhau/Dockerfile
  docker/docker-compose.base.yml
  docker/docker-compose.yml
  docker/resource-provider/Dockerfile
Labels: fix, cla-signed

#466 chore: CLA signed
  .clabot
  NOTICES.md
Labels: chore

#471 feat: Add VRAM and disk space matching
  pkg/solver/matcher/match.go
  pkg/solver/matcher/matcher_test.go
Labels: feature, cla-signed

#474 chore: Sign CLA
  .clabot
  NOTICES.md
Labels: chore

#477 docs: Update local dev guide
  LOCAL_DEVELOPMENT.md
Labels: documentation, cla-signed

#476 chore: Cleanup run command output
  cmd/lilypad/run.go
Labels: chore, cla-signed

#472 feat: Add download files signature check
  pkg/http/utils.go
  pkg/solver/server.go
Labels: feature, cla-signed
