Repository Lilypad-Tech/lilypad, pull requests merged in 2024-06, with the labels that each got.

#169 chore: Add PR title validation
  .github/workflows/validate_pr_title.yml
Labels: chore

#177 fix: blocked error channel
  pkg/mediator/controller.go
  pkg/resourceprovider/controller.go
Labels: fix

#178 feat: cuda miner support 2
  .github/workflows/darwin_amd64.yml
  .github/workflows/darwin_arm64.yml
  .github/workflows/linux_amd64.yml
  .github/workflows/linux_arm64.yml
  .github/workflows/release_binaries.yml
  go.mod
  go.sum
  pkg/options/resource-provider.go
  pkg/resourceprovider/cpuworker.go
  pkg/resourceprovider/cpuworker_test.go
  pkg/resourceprovider/cudaminer/config.h
  pkg/resourceprovider/cudaminer/keccak.cu
  pkg/resourceprovider/cudaminer/keccak.cuh
  pkg/resourceprovider/cudaminer/keccak.ptx
  pkg/resourceprovider/cudaworker.go
  pkg/resourceprovider/minerctl.go
  pkg/resourceprovider/others_os.go
  pkg/resourceprovider/resourceprovider.go
  pkg/resourceprovider/worker.go
Labels: feature

#179 fix: change workflow on condition to main
  .github/workflows/darwin_amd64.yml
  .github/workflows/darwin_arm64.yml
  .github/workflows/linux_amd64.yml
  .github/workflows/linux_arm64.yml
Labels: fix

#180 build: Update release_binaries.yml
  .github/workflows/release_binaries.yml
Labels: build

#182 perf: improve cuda pow
  go.mod
  go.sum
  hardhat/contracts/LilypadPow.sol
  pkg/resourceprovider/cudaminer/keccak.cu
  pkg/resourceprovider/cudaminer/keccak.ptx
  pkg/resourceprovider/cudaworker.go
  pkg/web3/bindings/pow/pow.go
Labels: performance

#188 fix: update embedded config
  pkg/options/configs/testnet.toml
Labels: fix

#189 build: update devnet deploys to manual
  .github/workflows/devnet_deploy.yml
Labels: build

#194 fix: tracking job offer update events
  pkg/jobcreator/controller.go
  pkg/jobcreator/onchain_jobcreator.go
  pkg/metricsDashboard/logger.go
Labels: fix

#197 chore: remove unused file
  docker/bacalhau/Dockerfile
Labels: chore

#199 feat: push RP docker image to registry
  .github/workflows/release_docker.yml
Labels: feature

#202 fix: correct worker number in log
  pkg/resourceprovider/minerctl.go
  pkg/resourceprovider/resourceprovider.go
Labels: fix

#193 feat: simply state loop in sc & fix typo
  hardhat/contracts/LilypadPow.sol
  pkg/web3/api.go
  pkg/web3/bindings/pow/pow.go
Labels: feature

#203 feat: default to enable pow
  pkg/options/resource-provider.go
  pkg/resourceprovider/resourceprovider.go
Labels: feature

#200 chore: Add release-please configs
  .release-please-manifest.json
  release-please-config.json
Labels: chore

#204 fix: update embeds
  pkg/options/configs/testnet.toml
Labels: fix

#207 build: Disable POW for local stack and Testnet resource provider
  .github/workflows/testnet_deploy_services.yml
  docker/resource-provider/Dockerfile
  stack
Labels: build

#192 fix: show bacalhau id error
  pkg/executor/bacalhau/bacalhau.go
  pkg/resourceprovider/resourceprovider.go
Labels: fix

#210 feat: add logger for pow events
  pkg/http/utils.go
  pkg/metricsDashboard/logger.go
  pkg/powLogs/logger.go
Labels: feature

#213 feat(install): auto updating binary
  ops/lilypad-updater.sh
  ops/systemd/lilpad-updater.timer
  ops/systemd/lilypad-updater.service
Labels: feature

#212 fix: pow proxy deployment
  .github/workflows/testnet_deploy_contracts.yml
  hardhat/.openzeppelin/unknown-412346.json
  hardhat/.openzeppelin/unknown-421614.json
  hardhat/contracts/LilypadPow.sol
  hardhat/deploy/009_proxy_upgrade.ts
  hardhat/hardhat.config.ts
  hardhat/package-lock.json
  hardhat/package.json
  pkg/options/configs/testnet.toml
Labels: fix

#214 fix: pow issue
  pkg/executor/bacalhau/bacalhau.go
  pkg/resourceprovider/resourceprovider.go
  pkg/web3/api.go
Labels: fix
