Repository Lilypad-Tech/lilypad, pull requests merged in 2025-01, with the labels that each got.

#475 fix: Remove resource offers in DealNegotiating[0] state on disconnect
  pkg/solver/controller.go
  pkg/solver/server.go
Labels: fix, cla-signed

#480 chore: Improve get solver URL error message
  pkg/web3/api.go
Labels: chore, cla-signed

#441 feat: Upgrade to bacalhau 1.6
  .github/workflows/test.yml
  .local.dev
  cmd/lilypad/mediator.go
  cmd/lilypad/resource-provider.go
  cmd/lilypad/run.go
  docker/bacalhau/Dockerfile
  docker/docker-compose.base.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  docker/resource-provider/Dockerfile
  go.mod
  go.sum
  pkg/executor/bacalhau/bacalhau.go
  pkg/executor/bacalhau/client.go
  pkg/executor/utils.go
  pkg/options/bacalhau.go
  pkg/solver/controller.go
  pkg/solver/ratelimit_test.go
  pkg/solver/server.go
  pkg/system/log.go
  stack
  test/integration_test.go
Labels: feature, cla-signed

#484 fix: remove ipfs from docker compose
  docker/docker-compose.base.yml
  docker/docker-compose.yml
Labels: fix, cla-signed

#488 fix: bacalhau getID
  go.mod
  go.sum
  pkg/executor/bacalhau/client.go
Labels: fix, cla-signed

#489 fix: docker setup for RPs
  docker/docker-compose.yml
  docker/resource-provider/Dockerfile
Labels: fix, cla-signed

#482 refactor: use strings.EqualFold
  pkg/solver/store/memory/store.go
Labels: refactor, cla-signed

#487 feat: Add validation token endpoint
  go.mod
  go.sum
  pkg/http/types.go
  pkg/options/server.go
  pkg/solver/client.go
  pkg/solver/server.go
  stack
Labels: feature, cla-signed

#462 feat: Add solver database
  cmd/lilypad/solver.go
  docker/docker-compose.dev.yml
  go.mod
  go.sum
  pkg/jsonl/reader.go
  pkg/jsonl/writer.go
  pkg/options/solver.go
  pkg/options/store.go
  pkg/solver/solver.go
  pkg/solver/store/db/db.go
  pkg/solver/store/db/models.go
  pkg/solver/store/memory/store.go
  pkg/solver/store/store.go
  pkg/solver/store/store_test.go
  stack
Labels: feature, cla-signed

#495 feat: Add validation token key ID config
  pkg/http/types.go
  pkg/options/server.go
  pkg/solver/server.go
  stack
Labels: feature, cla-signed

#496 chore: Disable external dependencies for local dev
  .local.dev
  pkg/options/configs/dev.toml
  stack
Labels: chore, cla-signed

#499 chore: signed CLA jdelamare
  .clabot
  NOTICES.md
Labels: chore

#500 fix: silence usage text
  cmd/lilypad/mediator.go
  cmd/lilypad/pow_signal.go
  cmd/lilypad/resource-provider.go
  cmd/lilypad/run.go
  cmd/lilypad/solver.go
Labels: fix, cla-signed

#498 feat: Add Job Creator support endpoints to the Solver
  pkg/solver/server.go
Labels: feature, cla-signed, apis

#505 feat: Update solver database models to use milli timestamps
  pkg/solver/store/db/models.go
Labels: feature, cla-signed

#497 feat: Add matching sorts
  .github/workflows/bench.yml
  LOCAL_DEVELOPMENT.md
  README.md
  pkg/solver/controller.go
  pkg/solver/matcher/match.go
  pkg/solver/matcher/matcher.go
  pkg/solver/matcher/matcher_bench_test.go
  pkg/solver/matcher/matcher_test.go
  pkg/solver/matcher/testing.go
  pkg/solver/solver_test.go
  pkg/solver/store/db/db.go
  pkg/solver/store/memory/store.go
  pkg/solver/store/store.go
  pkg/solver/store/store_test.go
  pkg/solver/testing.go
  stack
Labels: feature, cla-signed
