Repository Lilypad-Tech/lilypad, pull requests merged in 2025-03, with the labels that each got.

#525 chore: Update demonet addresses
  pkg/options/configs/demonet.toml
Labels: chore, cla-signed

#526 feat: Add lilynext flag
  cmd/lilypad/jobcreator.go
  cmd/lilypad/resource-provider.go
  cmd/lilypad/root.go
  cmd/lilypad/run.go
  cmd/lilypad/solver.go
Labels: feature, cla-signed

#527 feat: Add contextual logger
  cmd/lilypad/solver.go
  pkg/solver/controller.go
  pkg/solver/matcher/match.go
  pkg/solver/matcher/matcher.go
  pkg/solver/metric.go
  pkg/solver/server.go
  pkg/solver/solver.go
  pkg/solver/solver_test.go
  pkg/solver/stats/jobrun.go
  pkg/solver/stats/stats.go
  pkg/system/context.go
  pkg/system/log.go
Labels: feature, cla-signed

#528 feat: Isolate job output in cli
  pkg/jobcreator/controller.go
  pkg/jobcreator/jobcreator.go
  pkg/jobcreator/run.go
Labels: feature, cla-signed

#536 feat: Enhance JobCreatorController to manage single job lifecycle
  pkg/jobcreator/controller.go
  pkg/jobcreator/jobcreator.go
  pkg/jobcreator/onchain_jobcreator.go
  pkg/jobcreator/run.go
Labels: feature, cla-signed

#538 hotfix: Fixes bug where incorrect id passed to GetDeal in jobOfferdownloadfiles
  pkg/solver/server.go
Labels: cla-signed, hotfix

#541 feat: Enhance job offer update handling to filter by job ID
  pkg/jobcreator/run.go
Labels: feature, cla-signed

#544 feat: Add minimum version check
  cmd/lilypad/solver.go
  pkg/http/types.go
  pkg/options/server.go
  pkg/solver/server.go
  pkg/solver/solver.go
  pkg/system/version.go
  pkg/system/version_test.go
Labels: feature, cla-signed

#546 chore: Log job offer CID at run start
  pkg/jobcreator/run.go
Labels: chore, cla-signed

#539 feat: Module Loading Improvements
  pkg/module/utils.go
  pkg/module/utils_test.go
  pkg/options/server.go
Labels: feature, cla-signed

#550 chore: Sign CLA 0xThresh
  NOTICES.md
Labels: chore

#551 chore: add myself to contributors
  .clabot
Labels: chore

#552 feat: Add minimum version check enabled option
  pkg/http/types.go
  pkg/options/server.go
  pkg/solver/server.go
Labels: feature, cla-signed

#545 fix: Prevent duplicate job offers
  go.mod
  go.sum
  pkg/data/data.go
  pkg/jobcreator/utils.go
Labels: fix, cla-signed, solver, job creation

#549 fix: Add explicit NVIDIA device reservation to Resource Provider docker compose
  docker/docker-compose.yml
Labels: fix, cla-signed

#547 feat: setup foundation for new protocol
  .local.dev
  pkg/options/configs/demonet.toml
  pkg/options/configs/dev.toml
  pkg/options/configs/devnet.toml
  pkg/options/configs/testnet.toml
  pkg/options/web3.go
  pkg/system/services.go
  pkg/web3/api.go
  pkg/web3/api_v2.go
  pkg/web3/bindingsV2/LilypadContractRegistry/LilypadContractRegistry.go
  pkg/web3/bindingsV2/LilypadModuleDirectory/LilypadModuleDirectory.go
  pkg/web3/bindingsV2/LilypadPaymentEngine/LilypadPaymentEngine.go
  pkg/web3/bindingsV2/LilypadProxy/LilypadProxy.go
  pkg/web3/bindingsV2/LilypadStorage/LilypadStorage.go
  pkg/web3/bindingsV2/LilypadToken/LilypadToken.go
  pkg/web3/bindingsV2/LilypadTokenomics/LilypadTokenomics.go
  pkg/web3/bindingsV2/LilypadUser/LilypadUser.go
  pkg/web3/sdk.go
  pkg/web3/sdk_v2.go
  pkg/web3/types.go
Labels: feature, cla-signed

#554 fix: Exempt Anura from version check
  pkg/http/utils.go
  pkg/solver/server.go
Labels: fix, cla-signed

#558 feat: sign CLA for B0bbyDowns
  .clabot
  NOTICES.md
Labels: feature

#557 feat: Compute and report job run timings
  pkg/data/data.go
  pkg/data/utils.go
  pkg/solver/controller.go
  pkg/solver/server.go
  pkg/solver/solver.go
  pkg/solver/stats/jobrun.go
  pkg/solver/stats/reputation.go
  pkg/solver/stats/stats.go
  pkg/solver/store/db/db.go
  pkg/solver/store/memory/store.go
  pkg/solver/store/store.go
  pkg/solver/store/store_test.go
Labels: feature, cla-signed

#561 chore: updates bindings for v2 version of contracts
  pkg/web3/bindingsV2/LilypadContractRegistry/LilypadContractRegistry.go
  pkg/web3/bindingsV2/LilypadPaymentEngine/LilypadPaymentEngine.go
  pkg/web3/bindingsV2/LilypadProxy/LilypadProxy.go
  pkg/web3/bindingsV2/LilypadTokenomics/LilypadTokenomics.go
  pkg/web3/bindingsV2/LilypadUser/LilypadUser.go
Labels: chore, cla-signed
