Repository Lilypad-Tech/lilypad, pull requests merged in 2025-05, with the labels that each got.

#573 feat: Add job file inputs
  .github/workflows/test.yml
  docker/docker-compose.base.yml
  docker/docker-compose.yml
  go.mod
  go.sum
  pkg/data/data.go
  pkg/executor/bacalhau/bacalhau.go
  pkg/executor/bacalhau/client.go
  pkg/http/types.go
  pkg/http/utils.go
  pkg/jobcreator/controller.go
  pkg/jobcreator/jobcreator.go
  pkg/jobcreator/run.go
  pkg/jobcreator/utils.go
  pkg/module/utils.go
  pkg/options/job-creator.go
  pkg/options/server.go
  pkg/resourceprovider/controller.go
  pkg/solver/client.go
  pkg/solver/metric.go
  pkg/solver/server.go
  pkg/solver/solver.go
  pkg/solver/utils.go
Labels: feature, cla-signed

#576 feat: Add job offer max capacity check
  pkg/http/types.go
  pkg/options/server.go
  pkg/solver/server.go
Labels: feature, cla-signed

#578 fix: Exclude cancelled jobs from max job offer capacity
  pkg/solver/server.go
Labels: fix, cla-signed

#579 fix: version ARGs for RP Dockerfile
  docker/resource-provider/Dockerfile
Labels: fix, cla-signed

#582 chore: Increase test solver wait time
  .github/workflows/test.yml
Labels: chore, cla-signed

#581 perf: Remove supported modules check from solver matching algorithm
  pkg/options/resource-provider.go
  pkg/solver/matcher/match.go
  pkg/solver/matcher/testing.go
Labels: performance, cla-signed

#583 fix: add GPU access to Bacalhau in docker-compose.yml
  docker/docker-compose.yml
Labels: fix, cla-signed
